package org.gedcomx.persistence.graph.neo4j.utils;

public enum NodeTypes {
	CONCLUSION, AGENT, SOURCE_DESCRIPTION, ADDRESS, ACCOUNT, RELATIONSHIP, PLACE_DESCRIPTION, PERSON, NAME, FACT, EVENT, DOCUMENT, TEXT_VALUE, IDENTIFIER, NOTE, SOURCE_REFERENCE, PLACE, PLACE_REFERENCE, NAME_FORM, NAME_PART, EVENT_ROLE, GENDER, SOURCE_CITATION, CITATION_FIELD, ATTRIBUTION;
}
