package org.gedcomx.persistence.graph.neo4j.model.constants;

import org.neo4j.graphdb.Label;

public enum NodeTypes implements Label {
	GEDCOMX_MODEL, CONCLUSION, AGENT, SOURCE_DESCRIPTION, ADDRESS, ACCOUNT, RELATIONSHIP, PLACE_DESCRIPTION, PERSON, NAME, FACT, EVENT, DOCUMENT, TEXT_VALUE, IDENTIFIER, NOTE, SOURCE_REFERENCE, PLACE_REFERENCE, NAME_FORM, NAME_PART, EVENT_ROLE, GENDER, SOURCE_CITATION, CITATION_FIELD, ATTRIBUTION, QUALIFIER;
}
